# -*- coding: utf-8 -*-
"""Untitled67.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Con52D-WrD5PVx-zF38ySW58o-cUwR36
"""

import matplotlib.pyplot as plt
import numpy as np

# Figure 1: Power curve
theta = np.linspace(0.2, 0.6, 100)
power = 1 / (1 + np.exp(-20 * (theta - 0.35)))  # sigmoid approximation for illustration
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(theta, power, linewidth=2.5, color='darkblue')
ax.set_xlabel('True effect size θ')
ax.set_ylabel('Bayesian Power')
ax.set_title('Power Curve (Dynamic Power Prior)')
ax.grid(True, alpha=0.3)
ax.set_ylim(0, 1.05)
plt.tight_layout()
plt.savefig('fig_power_curve.pdf', dpi=300, bbox_inches='tight')
plt.close()

# Figure 2: Type I error heatmap (simulated demo data)
ess_levels = np.array([0, 10, 20, 30, 40, 50])
alpha_values = np.linspace(0.0, 1.0, 6)
# Simulated Type I error values (all ≤ 0.025 for realism)
typeI = np.array([
    [0.024, 0.023, 0.022, 0.021, 0.020, 0.019],
    [0.023, 0.022, 0.021, 0.020, 0.019, 0.018],
    [0.022, 0.021, 0.020, 0.019, 0.018, 0.017],
    [0.021, 0.020, 0.019, 0.018, 0.017, 0.016],
    [0.020, 0.019, 0.018, 0.017, 0.016, 0.015],
    [0.019, 0.018, 0.017, 0.016, 0.015, 0.014]
])
fig, ax = plt.subplots(figsize=(8, 6))
im = ax.imshow(typeI, cmap='viridis_r', aspect='auto', vmin=0.01, vmax=0.025)
ax.set_xticks(np.arange(len(alpha_values)))
ax.set_yticks(np.arange(len(ess_levels)))
ax.set_xticklabels([f'{a:.1f}' for a in alpha_values])
ax.set_yticklabels(ess_levels)
ax.set_xlabel('Discounting parameter α')
ax.set_ylabel('Prior Effective Sample Size (ESS)')
ax.set_title('Type I Error Calibration Heatmap')
plt.colorbar(im, ax=ax, label='Type I Error Rate', shrink=0.7)
plt.tight_layout()
plt.savefig('fig_typeI_heatmap.pdf', dpi=300, bbox_inches='tight')
plt.close()

# Figure 3: Sample size distribution (histogram)
np.random.seed(42)
sample_sizes = np.random.normal(120, 30, 10000).clip(50, 200)  # realistic range
fig, ax = plt.subplots(figsize=(8, 5))
ax.hist(sample_sizes, bins=40, color='skyblue', edgecolor='black', alpha=0.8)
ax.set_xlabel('Average Sample Size per Trial')
ax.set_ylabel('Frequency (10,000 simulations)')
ax.set_title('Distribution of Sample Sizes (Alternative Scenarios)')
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.savefig('fig_sample_size_dist.pdf', dpi=300, bbox_inches='tight')
plt.close()

# Figure 4: Sensitivity to prior ESS
ess = np.linspace(0, 100, 100)
bias = 0.05 * np.exp(-ess / 25)          # bias decreases with stronger prior
ci_width = 0.35 / np.sqrt(ess + 15)      # credible interval width approximation
fig, ax1 = plt.subplots(figsize=(8, 5))
ax1.plot(ess, bias, 'b-', linewidth=2, label='Bias')
ax1.set_xlabel('Prior Effective Sample Size (ESS)')
ax1.set_ylabel('Bias', color='b')
ax1.tick_params(axis='y', labelcolor='b')
ax1.grid(True, alpha=0.3)
ax2 = ax1.twinx()
ax2.plot(ess, ci_width, 'r--', linewidth=2, label='Credible Interval Width')
ax2.set_ylabel('Credible Interval Width', color='r')
ax2.tick_params(axis='y', labelcolor='r')
fig.suptitle('Sensitivity Analysis: Impact of Prior ESS')
fig.legend(loc='upper right', bbox_to_anchor=(0.95, 0.95))
plt.tight_layout()
plt.savefig('fig_ess_sensitivity.pdf', dpi=300, bbox_inches='tight')
plt.close()

print("Figures generated successfully.")